version: 2

project_name: echovault

builds:
  - binary: memory
    main: ./cmd/memory/
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # No widely-available cross-compiler for Windows arm64.
      - goos: windows
        goarch: arm64
    overrides:
      # Windows cross-compilation from Linux requires MinGW.
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
      # Linux arm64 cross-compilation from amd64.
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: go-ports
    name: echovault
  header: |
    ## echovault {{ .Version }}

    Release of echovault {{ .Version }}.

    ### Installation

    ```bash
    go install github.com/go-ports/echovault/cmd/memory@{{ .Tag }}
    ```

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'
