version: 2

project_name: echovault

builds:
  - binary: memory
    main: ./cmd/memory/
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - '6'
      - '7'
    ignore:
      # macOS does not support 32-bit ARM.
      - goos: darwin
        goarch: arm
      # 32-bit ARM Windows is effectively obsolete; deprecated in Go 1.25.
      - goos: windows
        goarch: arm
    overrides:
      # Linux targets are cross-compiled via zig (musl libc for portability).
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=zig-cc-x86_64-linux-musl
          - CXX=zig-cxx-x86_64-linux-musl
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=zig-cc-aarch64-linux-musl
          - CXX=zig-cxx-aarch64-linux-musl
      - goos: linux
        goarch: arm
        goarm: '6'
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=zig-cc-arm-linux-musleabi
          - CXX=zig-cxx-arm-linux-musleabi
      - goos: linux
        goarch: arm
        goarm: '7'
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=zig-cc-arm-linux-musleabihf
          - CXX=zig-cxx-arm-linux-musleabihf
      # Windows targets are cross-compiled via zig.
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=zig-cc-x86_64-windows-gnu
          - CXX=zig-cxx-x86_64-windows-gnu
      - goos: windows
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-DSQLITE_ENABLE_FTS5
          - CC=zig-cc-aarch64-windows-gnu
          - CXX=zig-cxx-aarch64-windows-gnu
      # darwin targets use native Xcode clang — no CC override needed.

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: go-ports
    name: echovault
  header: |
    ## echovault {{ .Version }}

    Release of echovault {{ .Version }}.

    ### Installation

    ```bash
    go install github.com/go-ports/echovault/cmd/memory@{{ .Tag }}
    ```

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'
